# Generated by Django 6.0.3 on 2026-04-08 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagnoses/')),
                ('plant_name', models.CharField(blank=True, max_length=200)),
                ('disease_name', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('is_healthy', models.BooleanField(default=False)),
                ('severity', models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('mild', 'Mild'), ('severe', 'Severe')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
